### ISSUE TITLE
no options available...

### ISSUE THREAD

**Issue by anibal-aguila** [brpaz/ulauncher-pwgen#3] opened 2019-05-28 08:04 UTC
I have installed pwgen but don't have an option on the launcher... 

```
❯ which pwgen
/home/user/.local/bin/pwgen

```

![image](https://user-images.githubusercontent.com/49025536/58461370-cc260300-812f-11e9-8d3f-d65cadef4b06.png)

**Comment by brpaz** [comment] 2019-06-22 10:05
This extension requires the python module of pwgen. you can install it using ```pip install pwgen``` or ```pip3 install pwgen```.

Using the command version might be implementing after merging #2

**Comment by anibal-aguila** [comment] 2019-06-26 14:54
> This extension requires the python module of pwgen. you can install it using `pip install pwgen` or `pip3 install pwgen`.
> 
> Using the command version might be implementing after merging #2

❯ pip3 install pwgen
Requirement already satisfied: pwgen in ./useraa/.local/lib/python3.7/site-packages (0.8.2.post0)

**Comment by brpaz** [comment] 2019-07-21 11:03
Hello. 
First try to update the extension. I have released a new version.

If it doesnt work, Can you try stopping ulauncher and run it from the command line like this:

```
ulauncher -v |& grep "pwgen"
```
and try to execute the extension to see what appears in the logs.

**Comment by brpaz** [comment] 2020-06-02 20:28
The latest version of ulauncher shows a better error message on the case of missing packages. I will close this issue.

The cause of this error is always a missing Python package.

Feel free to reopen if the problem persists.

**Closed as completed by brpaz** 2020-06-02 20:28 UTC
